name: Send fastmrt dataset link email on form submission
on:
  repository_dispatch:
    types: [form_submission]
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Send email
      run: |
        docker run --rm -e FASTMRT_EMAIL=$FASTMRT_EMAIL -e FASTMRT_EMAIL_PASSWARD=$FASTMRT_EMAIL_PASSWARD -v $(pwd):/app -w /app python:3 python send_email.py "${{ github.event.client_payload.name }}" "${{ github.event.client_payload.email }}" "${{ github.event.client_payload.message }}"
